//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/_System/Player/Scripts/joystickControl/joystickControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @JoystickControl : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @JoystickControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""joystickControl"",
    ""maps"": [
        {
            ""name"": ""P1Control"",
            ""id"": ""078d26a4-c160-41f5-b52e-0fe211842e87"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""09569ab5-d2cc-411a-9cb0-b9b2c2cc650e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RotateMouse"",
                    ""type"": ""PassThrough"",
                    ""id"": ""17837a79-21c8-4e51-a205-3ff74b5707b0"",
                    ""expectedControlType"": """",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""75cfe72e-1fd2-4896-9c10-1dec78da6cca"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Push"",
                    ""type"": ""Button"",
                    ""id"": ""5f03c65b-64a4-44a8-8964-77e02b741b91"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SuccFriendlyObject"",
                    ""type"": ""Button"",
                    ""id"": ""3e5edc09-041b-4b26-9862-f9cb2788ec7a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""dfcaff73-5a2c-4444-96a5-de3fb2825550"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LockBoss"",
                    ""type"": ""Button"",
                    ""id"": ""496582f0-f095-4d4a-ae20-43e8151abe1b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Respawn"",
                    ""type"": ""Button"",
                    ""id"": ""231acc1b-0308-4b81-b551-f77557c42a9d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c05d4a63-f76a-4920-9de7-c7d7b3cc18fc"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone(min=0.3,max=1)"",
                    ""groups"": ""JoyStick"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Arow"",
                    ""id"": ""e2ef9b71-6ab4-48c8-9b7d-75318f289f87"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9bbc0806-045d-43b1-a2b0-bd7276dde470"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse And Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5e59f505-c348-48cb-9ea2-aa492f990e29"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse And Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0dfc9185-a9a0-4798-868d-76f083da9f53"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse And Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4914562b-a7a2-4a90-a674-c4114d7c7178"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse And Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""161c9923-8f05-4e77-9d92-dd0f8b498bf4"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone(min=0.3,max=1)"",
                    ""groups"": ""JoyStick"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c76c62e9-b587-4f58-85d0-92769dce0b49"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""JoyStick"",
                    ""action"": ""Push"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f69ff5c-ae15-4b8a-9435-b320078be653"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""JoyStick"",
                    ""action"": ""Push"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d73b0402-601c-4586-b5af-f56140cfb7d9"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse And Keyboard"",
                    ""action"": ""Push"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""743d5509-2dd6-46d3-96ab-1937d25bb2e6"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse And Keyboard"",
                    ""action"": ""SuccFriendlyObject"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab6578df-260a-4699-88c9-d7cfd4b9e351"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""JoyStick"",
                    ""action"": ""SuccFriendlyObject"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2eac9f95-4eb9-4156-8d00-05805c3805b1"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""JoyStick"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a22990f-a706-4780-92c9-ac6c996320e3"",
                    ""path"": ""<Keyboard>/numpad0"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Mouse And Keyboard"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95149937-3e09-4cdc-b2fc-2a49768a1fb0"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a6dd4d6-de14-430d-9ce3-8d040d262e23"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""JoyStick"",
                    ""action"": ""LockBoss"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1ff0bf5-bafd-4932-be04-0071c8937fa1"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse And Keyboard"",
                    ""action"": ""RotateMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""afaffb37-830f-47e5-818b-9dea1ab9a1c3"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""JoyStick"",
                    ""action"": ""Respawn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ed8f9fa-f7dd-43ba-b247-8d92b2b0914f"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse And Keyboard"",
                    ""action"": ""Respawn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""P2Control"",
            ""id"": ""d3f177e6-af13-4ae8-8f1c-f661ccecdb9f"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""f5b34b81-0605-4f33-b185-971385ba5838"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RotateMouse"",
                    ""type"": ""PassThrough"",
                    ""id"": ""53c48b9b-20b4-40cb-82d7-7afb3f387ab2"",
                    ""expectedControlType"": """",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""de01ca48-e6fc-41a2-8a40-c04f703063b3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Push"",
                    ""type"": ""Button"",
                    ""id"": ""13236695-fc8a-4d08-bd21-21f3101569e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SuccFriendlyObject"",
                    ""type"": ""Button"",
                    ""id"": ""e5e5cef8-93e8-4bd9-8925-b28078792160"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""fe53a8e0-6706-446a-987d-9f00b6f71342"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LockBoss"",
                    ""type"": ""Button"",
                    ""id"": ""2e291aea-f792-44f0-9051-6d519ef9bef8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Respawn"",
                    ""type"": ""Button"",
                    ""id"": ""78b8579c-2a26-4203-a23c-090d7fce0668"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7c6ca1cb-c00e-4a22-a082-471caab5bba2"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone(min=0.3,max=1)"",
                    ""groups"": ""JoyStick"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Arow"",
                    ""id"": ""444e80f7-254b-463a-b542-332cf7633609"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""35bb4f8b-e679-474d-8efc-c1bf01573596"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse And Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""92d7f30b-a63b-4fea-ac60-5aa44e55d896"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse And Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c712459f-3a14-4156-99c9-0355f2a776c5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse And Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""bcdf15e1-72ac-433e-b115-a08442a64743"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse And Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5837fec3-6640-4fb8-970a-1dc1abd56d15"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone(min=0.3,max=1)"",
                    ""groups"": ""JoyStick"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""471d53f1-b432-4e6f-845c-65b6958af4b5"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""JoyStick"",
                    ""action"": ""Push"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3303e341-6333-45b7-8f69-e978c440aaac"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""JoyStick"",
                    ""action"": ""Push"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87c05771-43e0-4c00-ab8d-15e76a3ae8f0"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse And Keyboard"",
                    ""action"": ""Push"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37ba01bb-5a36-41ec-ad65-770eebe50fda"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse And Keyboard"",
                    ""action"": ""SuccFriendlyObject"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8cc21047-b3b2-4759-8e64-3af9fa425d2e"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""JoyStick"",
                    ""action"": ""SuccFriendlyObject"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c4f253d7-6bff-4a50-85f5-d01742dc475e"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""JoyStick"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5e93f7a-d735-49e4-85c0-e66be6ae1557"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse And Keyboard"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""297f9354-4e91-4859-966c-98fb6c6e9077"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19886818-15c3-4946-835f-b91c222b91e1"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""JoyStick"",
                    ""action"": ""LockBoss"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9e9a5ed-becc-4db5-b758-45f0e299cf36"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse And Keyboard"",
                    ""action"": ""RotateMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4fed8f65-0661-49ce-9373-254d6c1b9a95"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""JoyStick"",
                    ""action"": ""Respawn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c4874f49-f8fb-411f-ae8b-f4e2480d549b"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse And Keyboard"",
                    ""action"": ""Respawn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UIControl"",
            ""id"": ""3b720408-aee3-4846-971e-45e65d8048d2"",
            ""actions"": [
                {
                    ""name"": ""Navigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5c22ff8c-8b79-45a4-815b-f6355384d264"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""709d3da5-bd46-495d-99d9-3324a81b8c2b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ff8c30c6-702d-43dd-a709-321e85345541"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""c35f835a-d53d-49ef-b147-38c08db94186"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""PassThrough"",
                    ""id"": ""94f77336-85c1-4578-a4e5-b6c325d60a5a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MiddleClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ed4a5311-6e55-4062-8bb0-74eac1f79486"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrackedDevicePosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""fb14cd93-d420-48a8-a68b-3fdbb0a1bb63"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrackedDeviceOrientation"",
                    ""type"": ""PassThrough"",
                    ""id"": ""453e88e4-7edc-4866-9e32-8773188817a1"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e964bb8f-9972-4b29-8553-f12cd69ce5fe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScrollWheel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""c0a95088-958e-436d-b150-d905cfb5db85"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""94e3f876-9ff5-4143-b727-60bb415ec318"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5e189935-6552-4471-8a23-4bcb23aa4d16"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c4237c9f-b3ee-454b-84ca-25f53577e917"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""39c64805-f5fb-438d-b2ac-dbf03d87029e"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3b695b2c-6f76-4a0e-9e98-03cb4f34ec16"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9952940f-ca84-4108-aa93-706155559722"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""50da730f-3ff3-430e-9c7a-8ce9247daf2f"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""43398dd1-1d3f-4549-bce7-f731fa0a1db3"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""da151025-d61c-48d3-8214-3e7f9fa6be49"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8b7eaa3f-266c-4733-8bd6-1ebd54366db3"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Joystick"",
                    ""id"": ""f7765d95-833f-47b2-bb97-e0217bbc42eb"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c11e0b84-e838-4f67-87ad-9a2f9e92f2f2"",
                    ""path"": ""<Joystick>/stick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b15adf5d-8471-4edf-9edf-ef694f33dde7"",
                    ""path"": ""<Joystick>/stick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""20a658c1-2c5f-47a6-ad00-738ed64d8ba0"",
                    ""path"": ""<Joystick>/stick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""df55f05a-5f39-403d-a650-e9a029c80886"",
                    ""path"": ""<Joystick>/stick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""25096557-2655-4e49-b328-a8a0dc0d5eb0"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""636737ff-f1df-4c51-b4fb-718a6b4934f5"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2fb24554-209b-4680-8609-268814c811a9"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3c96c7e5-cb61-4e1d-8ce8-689c1ae2da98"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d5cfe13a-0ced-4b34-876c-a3d0db4f471e"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8819721f-51ed-4827-9cb6-e0eb8a053be0"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7070c6d9-903f-47cf-b72a-abebc0cb7ed3"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f6013a58-ce92-4ffb-b4b7-bcf0e80ab991"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3bfd8afd-fb4d-43f8-8069-f2e1a07c84e6"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""10b92d30-b65c-4b71-9ba8-1fae5c72ec09"",
                    ""path"": ""*/{Submit}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9308162d-a95d-48d5-9afa-4d04f5d1d755"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7727b5f0-6fca-4455-bf3d-45bd30e89601"",
                    ""path"": ""<Pen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""508cb6e2-4b97-4486-83ce-06ef8e24040e"",
                    ""path"": ""<Touchscreen>/touch*/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touch"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a742124e-e32f-4ce3-aa6d-275afb23ede5"",
                    ""path"": ""*/{Cancel}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""caf27217-b999-4c46-8209-e9f3c3377ded"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""062dedad-57ec-4964-bcf8-5c8615c06bf1"",
                    ""path"": ""<Pen>/tip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8a23137-47ce-468f-a746-bfb6006410f9"",
                    ""path"": ""<Touchscreen>/touch*/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touch"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a2ea5fa-0321-443c-bb34-06da09a1816d"",
                    ""path"": ""<XRController>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1158a9b4-b689-453c-97ca-c2f4737d3e48"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""MiddleClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87288df8-5dfd-45a5-8fb0-2f0eed836755"",
                    ""path"": ""<XRController>/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""TrackedDevicePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ad8bc69-2bb2-47cd-adf1-3b37c5896204"",
                    ""path"": ""<XRController>/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""TrackedDeviceOrientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c2bcb519-2b29-4e67-a89a-f3338e3d63c2"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""462a4f88-9673-4b4b-85c1-fffaa43aab5e"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""ScrollWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Mouse And Keyboard"",
            ""bindingGroup"": ""Mouse And Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""JoyStick"",
            ""bindingGroup"": ""JoyStick"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Joystick>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // P1Control
        m_P1Control = asset.FindActionMap("P1Control", throwIfNotFound: true);
        m_P1Control_Move = m_P1Control.FindAction("Move", throwIfNotFound: true);
        m_P1Control_RotateMouse = m_P1Control.FindAction("RotateMouse", throwIfNotFound: true);
        m_P1Control_Rotate = m_P1Control.FindAction("Rotate", throwIfNotFound: true);
        m_P1Control_Push = m_P1Control.FindAction("Push", throwIfNotFound: true);
        m_P1Control_SuccFriendlyObject = m_P1Control.FindAction("SuccFriendlyObject", throwIfNotFound: true);
        m_P1Control_Dash = m_P1Control.FindAction("Dash", throwIfNotFound: true);
        m_P1Control_LockBoss = m_P1Control.FindAction("LockBoss", throwIfNotFound: true);
        m_P1Control_Respawn = m_P1Control.FindAction("Respawn", throwIfNotFound: true);
        // P2Control
        m_P2Control = asset.FindActionMap("P2Control", throwIfNotFound: true);
        m_P2Control_Move = m_P2Control.FindAction("Move", throwIfNotFound: true);
        m_P2Control_RotateMouse = m_P2Control.FindAction("RotateMouse", throwIfNotFound: true);
        m_P2Control_Rotate = m_P2Control.FindAction("Rotate", throwIfNotFound: true);
        m_P2Control_Push = m_P2Control.FindAction("Push", throwIfNotFound: true);
        m_P2Control_SuccFriendlyObject = m_P2Control.FindAction("SuccFriendlyObject", throwIfNotFound: true);
        m_P2Control_Dash = m_P2Control.FindAction("Dash", throwIfNotFound: true);
        m_P2Control_LockBoss = m_P2Control.FindAction("LockBoss", throwIfNotFound: true);
        m_P2Control_Respawn = m_P2Control.FindAction("Respawn", throwIfNotFound: true);
        // UIControl
        m_UIControl = asset.FindActionMap("UIControl", throwIfNotFound: true);
        m_UIControl_Navigate = m_UIControl.FindAction("Navigate", throwIfNotFound: true);
        m_UIControl_Submit = m_UIControl.FindAction("Submit", throwIfNotFound: true);
        m_UIControl_Point = m_UIControl.FindAction("Point", throwIfNotFound: true);
        m_UIControl_Cancel = m_UIControl.FindAction("Cancel", throwIfNotFound: true);
        m_UIControl_Click = m_UIControl.FindAction("Click", throwIfNotFound: true);
        m_UIControl_MiddleClick = m_UIControl.FindAction("MiddleClick", throwIfNotFound: true);
        m_UIControl_TrackedDevicePosition = m_UIControl.FindAction("TrackedDevicePosition", throwIfNotFound: true);
        m_UIControl_TrackedDeviceOrientation = m_UIControl.FindAction("TrackedDeviceOrientation", throwIfNotFound: true);
        m_UIControl_RightClick = m_UIControl.FindAction("RightClick", throwIfNotFound: true);
        m_UIControl_ScrollWheel = m_UIControl.FindAction("ScrollWheel", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // P1Control
    private readonly InputActionMap m_P1Control;
    private IP1ControlActions m_P1ControlActionsCallbackInterface;
    private readonly InputAction m_P1Control_Move;
    private readonly InputAction m_P1Control_RotateMouse;
    private readonly InputAction m_P1Control_Rotate;
    private readonly InputAction m_P1Control_Push;
    private readonly InputAction m_P1Control_SuccFriendlyObject;
    private readonly InputAction m_P1Control_Dash;
    private readonly InputAction m_P1Control_LockBoss;
    private readonly InputAction m_P1Control_Respawn;
    public struct P1ControlActions
    {
        private @JoystickControl m_Wrapper;
        public P1ControlActions(@JoystickControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_P1Control_Move;
        public InputAction @RotateMouse => m_Wrapper.m_P1Control_RotateMouse;
        public InputAction @Rotate => m_Wrapper.m_P1Control_Rotate;
        public InputAction @Push => m_Wrapper.m_P1Control_Push;
        public InputAction @SuccFriendlyObject => m_Wrapper.m_P1Control_SuccFriendlyObject;
        public InputAction @Dash => m_Wrapper.m_P1Control_Dash;
        public InputAction @LockBoss => m_Wrapper.m_P1Control_LockBoss;
        public InputAction @Respawn => m_Wrapper.m_P1Control_Respawn;
        public InputActionMap Get() { return m_Wrapper.m_P1Control; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(P1ControlActions set) { return set.Get(); }
        public void SetCallbacks(IP1ControlActions instance)
        {
            if (m_Wrapper.m_P1ControlActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_P1ControlActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_P1ControlActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_P1ControlActionsCallbackInterface.OnMove;
                @RotateMouse.started -= m_Wrapper.m_P1ControlActionsCallbackInterface.OnRotateMouse;
                @RotateMouse.performed -= m_Wrapper.m_P1ControlActionsCallbackInterface.OnRotateMouse;
                @RotateMouse.canceled -= m_Wrapper.m_P1ControlActionsCallbackInterface.OnRotateMouse;
                @Rotate.started -= m_Wrapper.m_P1ControlActionsCallbackInterface.OnRotate;
                @Rotate.performed -= m_Wrapper.m_P1ControlActionsCallbackInterface.OnRotate;
                @Rotate.canceled -= m_Wrapper.m_P1ControlActionsCallbackInterface.OnRotate;
                @Push.started -= m_Wrapper.m_P1ControlActionsCallbackInterface.OnPush;
                @Push.performed -= m_Wrapper.m_P1ControlActionsCallbackInterface.OnPush;
                @Push.canceled -= m_Wrapper.m_P1ControlActionsCallbackInterface.OnPush;
                @SuccFriendlyObject.started -= m_Wrapper.m_P1ControlActionsCallbackInterface.OnSuccFriendlyObject;
                @SuccFriendlyObject.performed -= m_Wrapper.m_P1ControlActionsCallbackInterface.OnSuccFriendlyObject;
                @SuccFriendlyObject.canceled -= m_Wrapper.m_P1ControlActionsCallbackInterface.OnSuccFriendlyObject;
                @Dash.started -= m_Wrapper.m_P1ControlActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_P1ControlActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_P1ControlActionsCallbackInterface.OnDash;
                @LockBoss.started -= m_Wrapper.m_P1ControlActionsCallbackInterface.OnLockBoss;
                @LockBoss.performed -= m_Wrapper.m_P1ControlActionsCallbackInterface.OnLockBoss;
                @LockBoss.canceled -= m_Wrapper.m_P1ControlActionsCallbackInterface.OnLockBoss;
                @Respawn.started -= m_Wrapper.m_P1ControlActionsCallbackInterface.OnRespawn;
                @Respawn.performed -= m_Wrapper.m_P1ControlActionsCallbackInterface.OnRespawn;
                @Respawn.canceled -= m_Wrapper.m_P1ControlActionsCallbackInterface.OnRespawn;
            }
            m_Wrapper.m_P1ControlActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @RotateMouse.started += instance.OnRotateMouse;
                @RotateMouse.performed += instance.OnRotateMouse;
                @RotateMouse.canceled += instance.OnRotateMouse;
                @Rotate.started += instance.OnRotate;
                @Rotate.performed += instance.OnRotate;
                @Rotate.canceled += instance.OnRotate;
                @Push.started += instance.OnPush;
                @Push.performed += instance.OnPush;
                @Push.canceled += instance.OnPush;
                @SuccFriendlyObject.started += instance.OnSuccFriendlyObject;
                @SuccFriendlyObject.performed += instance.OnSuccFriendlyObject;
                @SuccFriendlyObject.canceled += instance.OnSuccFriendlyObject;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @LockBoss.started += instance.OnLockBoss;
                @LockBoss.performed += instance.OnLockBoss;
                @LockBoss.canceled += instance.OnLockBoss;
                @Respawn.started += instance.OnRespawn;
                @Respawn.performed += instance.OnRespawn;
                @Respawn.canceled += instance.OnRespawn;
            }
        }
    }
    public P1ControlActions @P1Control => new P1ControlActions(this);

    // P2Control
    private readonly InputActionMap m_P2Control;
    private IP2ControlActions m_P2ControlActionsCallbackInterface;
    private readonly InputAction m_P2Control_Move;
    private readonly InputAction m_P2Control_RotateMouse;
    private readonly InputAction m_P2Control_Rotate;
    private readonly InputAction m_P2Control_Push;
    private readonly InputAction m_P2Control_SuccFriendlyObject;
    private readonly InputAction m_P2Control_Dash;
    private readonly InputAction m_P2Control_LockBoss;
    private readonly InputAction m_P2Control_Respawn;
    public struct P2ControlActions
    {
        private @JoystickControl m_Wrapper;
        public P2ControlActions(@JoystickControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_P2Control_Move;
        public InputAction @RotateMouse => m_Wrapper.m_P2Control_RotateMouse;
        public InputAction @Rotate => m_Wrapper.m_P2Control_Rotate;
        public InputAction @Push => m_Wrapper.m_P2Control_Push;
        public InputAction @SuccFriendlyObject => m_Wrapper.m_P2Control_SuccFriendlyObject;
        public InputAction @Dash => m_Wrapper.m_P2Control_Dash;
        public InputAction @LockBoss => m_Wrapper.m_P2Control_LockBoss;
        public InputAction @Respawn => m_Wrapper.m_P2Control_Respawn;
        public InputActionMap Get() { return m_Wrapper.m_P2Control; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(P2ControlActions set) { return set.Get(); }
        public void SetCallbacks(IP2ControlActions instance)
        {
            if (m_Wrapper.m_P2ControlActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_P2ControlActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_P2ControlActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_P2ControlActionsCallbackInterface.OnMove;
                @RotateMouse.started -= m_Wrapper.m_P2ControlActionsCallbackInterface.OnRotateMouse;
                @RotateMouse.performed -= m_Wrapper.m_P2ControlActionsCallbackInterface.OnRotateMouse;
                @RotateMouse.canceled -= m_Wrapper.m_P2ControlActionsCallbackInterface.OnRotateMouse;
                @Rotate.started -= m_Wrapper.m_P2ControlActionsCallbackInterface.OnRotate;
                @Rotate.performed -= m_Wrapper.m_P2ControlActionsCallbackInterface.OnRotate;
                @Rotate.canceled -= m_Wrapper.m_P2ControlActionsCallbackInterface.OnRotate;
                @Push.started -= m_Wrapper.m_P2ControlActionsCallbackInterface.OnPush;
                @Push.performed -= m_Wrapper.m_P2ControlActionsCallbackInterface.OnPush;
                @Push.canceled -= m_Wrapper.m_P2ControlActionsCallbackInterface.OnPush;
                @SuccFriendlyObject.started -= m_Wrapper.m_P2ControlActionsCallbackInterface.OnSuccFriendlyObject;
                @SuccFriendlyObject.performed -= m_Wrapper.m_P2ControlActionsCallbackInterface.OnSuccFriendlyObject;
                @SuccFriendlyObject.canceled -= m_Wrapper.m_P2ControlActionsCallbackInterface.OnSuccFriendlyObject;
                @Dash.started -= m_Wrapper.m_P2ControlActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_P2ControlActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_P2ControlActionsCallbackInterface.OnDash;
                @LockBoss.started -= m_Wrapper.m_P2ControlActionsCallbackInterface.OnLockBoss;
                @LockBoss.performed -= m_Wrapper.m_P2ControlActionsCallbackInterface.OnLockBoss;
                @LockBoss.canceled -= m_Wrapper.m_P2ControlActionsCallbackInterface.OnLockBoss;
                @Respawn.started -= m_Wrapper.m_P2ControlActionsCallbackInterface.OnRespawn;
                @Respawn.performed -= m_Wrapper.m_P2ControlActionsCallbackInterface.OnRespawn;
                @Respawn.canceled -= m_Wrapper.m_P2ControlActionsCallbackInterface.OnRespawn;
            }
            m_Wrapper.m_P2ControlActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @RotateMouse.started += instance.OnRotateMouse;
                @RotateMouse.performed += instance.OnRotateMouse;
                @RotateMouse.canceled += instance.OnRotateMouse;
                @Rotate.started += instance.OnRotate;
                @Rotate.performed += instance.OnRotate;
                @Rotate.canceled += instance.OnRotate;
                @Push.started += instance.OnPush;
                @Push.performed += instance.OnPush;
                @Push.canceled += instance.OnPush;
                @SuccFriendlyObject.started += instance.OnSuccFriendlyObject;
                @SuccFriendlyObject.performed += instance.OnSuccFriendlyObject;
                @SuccFriendlyObject.canceled += instance.OnSuccFriendlyObject;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @LockBoss.started += instance.OnLockBoss;
                @LockBoss.performed += instance.OnLockBoss;
                @LockBoss.canceled += instance.OnLockBoss;
                @Respawn.started += instance.OnRespawn;
                @Respawn.performed += instance.OnRespawn;
                @Respawn.canceled += instance.OnRespawn;
            }
        }
    }
    public P2ControlActions @P2Control => new P2ControlActions(this);

    // UIControl
    private readonly InputActionMap m_UIControl;
    private IUIControlActions m_UIControlActionsCallbackInterface;
    private readonly InputAction m_UIControl_Navigate;
    private readonly InputAction m_UIControl_Submit;
    private readonly InputAction m_UIControl_Point;
    private readonly InputAction m_UIControl_Cancel;
    private readonly InputAction m_UIControl_Click;
    private readonly InputAction m_UIControl_MiddleClick;
    private readonly InputAction m_UIControl_TrackedDevicePosition;
    private readonly InputAction m_UIControl_TrackedDeviceOrientation;
    private readonly InputAction m_UIControl_RightClick;
    private readonly InputAction m_UIControl_ScrollWheel;
    public struct UIControlActions
    {
        private @JoystickControl m_Wrapper;
        public UIControlActions(@JoystickControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @Navigate => m_Wrapper.m_UIControl_Navigate;
        public InputAction @Submit => m_Wrapper.m_UIControl_Submit;
        public InputAction @Point => m_Wrapper.m_UIControl_Point;
        public InputAction @Cancel => m_Wrapper.m_UIControl_Cancel;
        public InputAction @Click => m_Wrapper.m_UIControl_Click;
        public InputAction @MiddleClick => m_Wrapper.m_UIControl_MiddleClick;
        public InputAction @TrackedDevicePosition => m_Wrapper.m_UIControl_TrackedDevicePosition;
        public InputAction @TrackedDeviceOrientation => m_Wrapper.m_UIControl_TrackedDeviceOrientation;
        public InputAction @RightClick => m_Wrapper.m_UIControl_RightClick;
        public InputAction @ScrollWheel => m_Wrapper.m_UIControl_ScrollWheel;
        public InputActionMap Get() { return m_Wrapper.m_UIControl; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIControlActions set) { return set.Get(); }
        public void SetCallbacks(IUIControlActions instance)
        {
            if (m_Wrapper.m_UIControlActionsCallbackInterface != null)
            {
                @Navigate.started -= m_Wrapper.m_UIControlActionsCallbackInterface.OnNavigate;
                @Navigate.performed -= m_Wrapper.m_UIControlActionsCallbackInterface.OnNavigate;
                @Navigate.canceled -= m_Wrapper.m_UIControlActionsCallbackInterface.OnNavigate;
                @Submit.started -= m_Wrapper.m_UIControlActionsCallbackInterface.OnSubmit;
                @Submit.performed -= m_Wrapper.m_UIControlActionsCallbackInterface.OnSubmit;
                @Submit.canceled -= m_Wrapper.m_UIControlActionsCallbackInterface.OnSubmit;
                @Point.started -= m_Wrapper.m_UIControlActionsCallbackInterface.OnPoint;
                @Point.performed -= m_Wrapper.m_UIControlActionsCallbackInterface.OnPoint;
                @Point.canceled -= m_Wrapper.m_UIControlActionsCallbackInterface.OnPoint;
                @Cancel.started -= m_Wrapper.m_UIControlActionsCallbackInterface.OnCancel;
                @Cancel.performed -= m_Wrapper.m_UIControlActionsCallbackInterface.OnCancel;
                @Cancel.canceled -= m_Wrapper.m_UIControlActionsCallbackInterface.OnCancel;
                @Click.started -= m_Wrapper.m_UIControlActionsCallbackInterface.OnClick;
                @Click.performed -= m_Wrapper.m_UIControlActionsCallbackInterface.OnClick;
                @Click.canceled -= m_Wrapper.m_UIControlActionsCallbackInterface.OnClick;
                @MiddleClick.started -= m_Wrapper.m_UIControlActionsCallbackInterface.OnMiddleClick;
                @MiddleClick.performed -= m_Wrapper.m_UIControlActionsCallbackInterface.OnMiddleClick;
                @MiddleClick.canceled -= m_Wrapper.m_UIControlActionsCallbackInterface.OnMiddleClick;
                @TrackedDevicePosition.started -= m_Wrapper.m_UIControlActionsCallbackInterface.OnTrackedDevicePosition;
                @TrackedDevicePosition.performed -= m_Wrapper.m_UIControlActionsCallbackInterface.OnTrackedDevicePosition;
                @TrackedDevicePosition.canceled -= m_Wrapper.m_UIControlActionsCallbackInterface.OnTrackedDevicePosition;
                @TrackedDeviceOrientation.started -= m_Wrapper.m_UIControlActionsCallbackInterface.OnTrackedDeviceOrientation;
                @TrackedDeviceOrientation.performed -= m_Wrapper.m_UIControlActionsCallbackInterface.OnTrackedDeviceOrientation;
                @TrackedDeviceOrientation.canceled -= m_Wrapper.m_UIControlActionsCallbackInterface.OnTrackedDeviceOrientation;
                @RightClick.started -= m_Wrapper.m_UIControlActionsCallbackInterface.OnRightClick;
                @RightClick.performed -= m_Wrapper.m_UIControlActionsCallbackInterface.OnRightClick;
                @RightClick.canceled -= m_Wrapper.m_UIControlActionsCallbackInterface.OnRightClick;
                @ScrollWheel.started -= m_Wrapper.m_UIControlActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.performed -= m_Wrapper.m_UIControlActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.canceled -= m_Wrapper.m_UIControlActionsCallbackInterface.OnScrollWheel;
            }
            m_Wrapper.m_UIControlActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Navigate.started += instance.OnNavigate;
                @Navigate.performed += instance.OnNavigate;
                @Navigate.canceled += instance.OnNavigate;
                @Submit.started += instance.OnSubmit;
                @Submit.performed += instance.OnSubmit;
                @Submit.canceled += instance.OnSubmit;
                @Point.started += instance.OnPoint;
                @Point.performed += instance.OnPoint;
                @Point.canceled += instance.OnPoint;
                @Cancel.started += instance.OnCancel;
                @Cancel.performed += instance.OnCancel;
                @Cancel.canceled += instance.OnCancel;
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
                @MiddleClick.started += instance.OnMiddleClick;
                @MiddleClick.performed += instance.OnMiddleClick;
                @MiddleClick.canceled += instance.OnMiddleClick;
                @TrackedDevicePosition.started += instance.OnTrackedDevicePosition;
                @TrackedDevicePosition.performed += instance.OnTrackedDevicePosition;
                @TrackedDevicePosition.canceled += instance.OnTrackedDevicePosition;
                @TrackedDeviceOrientation.started += instance.OnTrackedDeviceOrientation;
                @TrackedDeviceOrientation.performed += instance.OnTrackedDeviceOrientation;
                @TrackedDeviceOrientation.canceled += instance.OnTrackedDeviceOrientation;
                @RightClick.started += instance.OnRightClick;
                @RightClick.performed += instance.OnRightClick;
                @RightClick.canceled += instance.OnRightClick;
                @ScrollWheel.started += instance.OnScrollWheel;
                @ScrollWheel.performed += instance.OnScrollWheel;
                @ScrollWheel.canceled += instance.OnScrollWheel;
            }
        }
    }
    public UIControlActions @UIControl => new UIControlActions(this);
    private int m_MouseAndKeyboardSchemeIndex = -1;
    public InputControlScheme MouseAndKeyboardScheme
    {
        get
        {
            if (m_MouseAndKeyboardSchemeIndex == -1) m_MouseAndKeyboardSchemeIndex = asset.FindControlSchemeIndex("Mouse And Keyboard");
            return asset.controlSchemes[m_MouseAndKeyboardSchemeIndex];
        }
    }
    private int m_JoyStickSchemeIndex = -1;
    public InputControlScheme JoyStickScheme
    {
        get
        {
            if (m_JoyStickSchemeIndex == -1) m_JoyStickSchemeIndex = asset.FindControlSchemeIndex("JoyStick");
            return asset.controlSchemes[m_JoyStickSchemeIndex];
        }
    }
    public interface IP1ControlActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnRotateMouse(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
        void OnPush(InputAction.CallbackContext context);
        void OnSuccFriendlyObject(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnLockBoss(InputAction.CallbackContext context);
        void OnRespawn(InputAction.CallbackContext context);
    }
    public interface IP2ControlActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnRotateMouse(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
        void OnPush(InputAction.CallbackContext context);
        void OnSuccFriendlyObject(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnLockBoss(InputAction.CallbackContext context);
        void OnRespawn(InputAction.CallbackContext context);
    }
    public interface IUIControlActions
    {
        void OnNavigate(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
        void OnPoint(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
        void OnMiddleClick(InputAction.CallbackContext context);
        void OnTrackedDevicePosition(InputAction.CallbackContext context);
        void OnTrackedDeviceOrientation(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
        void OnScrollWheel(InputAction.CallbackContext context);
    }
}
